CREATE TABLE [dbo].[AppCustomerUser]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[AppCustomerId] BIGINT NOT NULL, 
	[FirstName] NVARCHAR(250) NULL,
	[LastName] NVARCHAR(250) NULL,
	[Email] NVARCHAR(250) NOT NULL,
	[Phone] NVARCHAR(250) NOT NULL,
	[LocaleCode] NVARCHAR(50) NULL,
	[AppUserId] BIGINT NULL, 
	[TimeStamp] DATETIME2 NOT NULL, 
CONSTRAINT [PK_AppCustomerUser] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [FK_AppCustomerUser_AppCustomer] FOREIGN KEY ([AppCustomerId]) REFERENCES [AppCustomer]([Id]), 
  CONSTRAINT [FK_AppCustomerUser_AppAuth] FOREIGN KEY ([AppUserId]) REFERENCES [AppUser]([Id]), 
) 
