CREATE TABLE [dbo].[AppConfig]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[AppConfigGroupId] BIGINT NOT NULL,
	[Code] NVARCHAR(50) NOT NULL,
	[Value] NVARCHAR(250) NOT NULL,
	[Description] NVARCHAR(250) NOT NULL,
CONSTRAINT [PK_AppConfig] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [FK_AppConfig_SettingGroup] FOREIGN KEY ([AppConfigGroupId]) REFERENCES [AppConfigGroup]([Id]), 
) 