CREATE TABLE [dbo].[AppLogin]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[LoginId] NVARCHAR(250) NOT NULL,
	[LoginSecret] NVARCHAR(max) NULL,
	[SecretKey] UNIQUEIDENTIFIER NULL,
	[DisplayName] NVARCHAR(250) NOT NULL,
	[FirstName] NVARCHAR(250) NULL,
	[LastName] NVARCHAR(250) NULL,
	[Email] NVARCHAR(250) NULL,
	[Phone] NVARCHAR(250) NULL,
	[ValidTill] DATETIME2 NULL, 
	[LastLoginTime] DATETIME2 NULL, 
	[TimeStamp] DATETIME2 NOT NULL, 
CONSTRAINT [PK_AppUser] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) 
