CREATE TABLE [dbo].[AppUserRefreshToken]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[AppUserId] BIGINT NOT NULL,
	[IssuedTime] DATETIME2 NOT NULL,
	[ExpiryTime] DATETIME2 NOT NULL,
	[SessionKey] UNIQUEIDENTIFIER NOT NULL,
	[RefreshToken] UNIQUEIDENTIFIER NOT NULL,
	[LastAccessedTime] DATETIME2 NOT NULL, 
	[TotalRenewals] INT NULL,
	[TimeStamp] DATETIME2 NOT NULL, 
CONSTRAINT [PK_AppUserRefreshToken] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [FK_AppUserRefreshToken_AppUser] FOREIGN KEY ([AppUserId]) REFERENCES [AppUser]([Id]), 
) 
