CREATE TABLE [dbo].[AppUser]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[AppCustomerId] BIGINT NOT NULL, 
	[AppUserTypeId] BIGINT NOT NULL,
	[AuthId] NVARCHAR(250) NOT NULL,
	[AuthSecret] NVARCHAR(max) NULL,
	[SecretKey] UNIQUEIDENTIFIER NULL,
	[DisplayName] NVARCHAR(250) NOT NULL,
	[LoginTime] DATETIME2 NULL,
	[TimeStamp] DATETIME2 NOT NULL, 
CONSTRAINT [PK_AppUser] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [FK_AppUser_AppAuthType] FOREIGN KEY ([AppUserTypeId]) REFERENCES [AppUserType]([Id]), 
  CONSTRAINT [FK_AppUser_AppCustomer] FOREIGN KEY ([AppCustomerId]) REFERENCES [AppCustomer]([Id]), 
) 
