CREATE TABLE [dbo].[LanguageGroup]
(
	[Id] BIGINT IDENTITY NOT NULL,
	[WMSApplicationId] BIGINT, 
	[Code] NVARCHAR(50) NOT NULL,
	[Name] NVARCHAR(250) NOT NULL,
	[TimeStamp] DATETIME NOT NULL, 
    CONSTRAINT [PK_LanguageGroup] PRIMARY KEY CLUSTERED( [Id] ASC
 ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) 


